title: Stamatis Klonaris
logo: /assets/img/heatshot_circle.png
description: Hey everyone, here is my personal portfolio website that I created to show you my projects. Please enjoy!!! 
show_downloads: true
theme: jekyll-theme-minimal
